version: "3"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686" #This port is the jaeger UI
      - "4317:4317/tcp" #This port is the grpc collector
      - "4318:4318/tcp" #This port is the http collector
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"